---
- name: this playbook install http and to restart also
  hosts: all
  become: true
  tasks:
  - name: install package
    yum:
      name: httpd
      state: installed  
    when: ansible_os_family == "RedHat"
  - name: start apache
    service:
       name: httpd
       state: started
    when: ansible_os_family == "RedHat"

  - name: install apache2
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"

  - name: start apache2 service
    service:
       name: apache2
       state: started
    when: ansible_os_family == "Debian"

