---
- name: this playbook uninstall httpd
  hosts: all
  become: true
  tasks:

  - name: stop httpd service
    service:
       name: httpd
       state: stopped
    when: ansible_os_family == 'Redhat'

  - name: uninstalled httpd
    yum:
      name: httpd
      state: removed
    when: ansible_os_family == 'Redhat'

  - name: stop apache2 service
    service:
       name: apache2
       state: stopped
    when: ansible_os_family == 'Debian'

  - name: uninstalled apache2
    apt:
      name: apache2
      state: absent
    when: ansible_os_family == 'Debian'



  - name: stop httpd service
    service:
       name: httpd
       state: stopped

  - name: uninstalled httpd
    yum:
      name: httpd
      state: removed


